apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webpagedesign
  template:
    metadata:
      labels: 
        app: webpagedesign
        environment: dev
    spec:
       containers:
        - name: website
          image: mehrjay86/webpagedesign
          ports:
            - containerPort: 8080
